### ISSUE TITLE
make error: json/json.hpp: No such file or directory

### ISSUE THREAD

**Issue by yunmengren** [avast/yarang#1]
<yaramod install dir>/include/yaramod/utils/json.h:9:10: fatal error: json/json.hpp: No such file or directory
Why can't find json.hpp
How can i solve this problem

**Comment by metthal** [comment]
How did you install [yaramod](https://github.com/avast/yaramod)? I recommend doing something like this

```
git clone git@github.com:avast/yaramod.git && cd yaramod
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install ..
cmake --build . --target install -- -j
```

and then in yarang

```
mkdir build && cd build
cmake -DYARAMOD_ROOT_DIR=<PATH_TO_YARAMOD>/install ..
cmake --build . -- -j
```

It should take care of everything and you shouldn't have to install anything additional.

**Comment by yunmengren** [comment]
Thx, I did install yaramod as recommended, but solved the yarang build problem by upgrading the g++ version (g++ 9.3.0 => 10.3.0)
